import type { CardId } from './types'

/**
 * The canonical 44-card deck (rules.md: no jokers, no red face cards,
 * no red aces). Order here is canonical, not shuffle order.
 * Generated from the artwork filenames in src/assets/cards/.
 */
export const CARD_IDS = [
  'club-2',
  'club-3',
  'club-4',
  'club-5',
  'club-6',
  'club-7',
  'club-8',
  'club-9',
  'club-10',
  'club-j',
  'club-q',
  'club-k',
  'club-a',
  'spade-2',
  'spade-3',
  'spade-4',
  'spade-5',
  'spade-6',
  'spade-7',
  'spade-8',
  'spade-9',
  'spade-10',
  'spade-j',
  'spade-q',
  'spade-k',
  'spade-a',
  'diamond-2',
  'diamond-3',
  'diamond-4',
  'diamond-5',
  'diamond-6',
  'diamond-7',
  'diamond-8',
  'diamond-9',
  'diamond-10',
  'heart-2',
  'heart-3',
  'heart-4',
  'heart-5',
  'heart-6',
  'heart-7',
  'heart-8',
  'heart-9',
  'heart-10',
] as const satisfies readonly CardId[]
